### ISSUE TITLE
Add a readme file?

### ISSUE THREAD

**Issue by jcs090218** [udyantw/most-used-words#2]
Would it be great if there is a README file to introduce this great package?! Thanks for this great package though! 😄

**Comment by udyantw** [comment]
Thanks for your compliment! I've added a README. I didn't think I could improve on the commenary in the source itself. But let me know if it needs something else.

**Comment by jcs090218** [comment]
Thanks! I think you could write the README file using markdown, so it looks a bit nicer in GitHub! Anyway, I think this has a minimal information for people to get notice to this package. Great work! :)

**Comment by udyantw** [comment]
I've prepared a mildly formatted Markdown README.md. Please have a look.

**Comment by jcs090218** [comment]
Thanks! This is way better than a plain text file! I think this is good enough for now! 😄 

You might want to change this on the way of further development.
