### ISSUE TITLE
Display count and percentage.

### ISSUE THREAD

**Issue by jcs090218** [udyantw/most-used-words#3]
I think this feature would be great to see. Maybe like the example below!

```
word    5      50%
buffer   3     30%
hello    2      20%
```

**Comment by udyantw** [comment]
I'm working on it. I've made it so that a prefix argument will produce a buffer of words and their counts and percentages: C-u M-x most-used-words-buffer
This allows the unprefixed call to produce the bare buffer of frequent words.

**Comment by jcs090218** [comment]
Hopefully this could get done soon! And I am very appreciate your work! Thanks! 😄

**Comment by udyantw** [comment]
Thanks. I've added the functionality. Please check.

I've also noted the feature in the README.

**Comment by jcs090218** [comment]
Cool! But do you use it? I have tried by calling with buffer but with no effect! 😕 

I think it would be great if there is a `defcustom` that is boolean and tweakable for user to decide to display the percentages or not. BTW, thanks! 😄

**Comment by udyantw** [comment]
If I understand, when you issue the command M-x most-used-words-buffer, Emacs prompts you for the number of words, but then proceeds to do nothing. Is that right? Or do you see something else?

**Comment by jcs090218** [comment]
> If I understand, when you issue the command M-x most-used-words-buffer, Emacs prompts you for the number of words, but then proceeds to do nothing. Is that right? Or do you see something else?

I tried the command `most-used-words-buffer` but it appear to be the same. Meaning it does not display percentages or counts. 😕

**Comment by udyantw** [comment]
I get it. You have to use C-u M-x most-used-words-buffer to get the percentages. Let me know if it works for you.

**Comment by jcs090218** [comment]
I was expecting a variable that may be hold the option to display more information. Like

```el
;; variable that holds the option.
(defcustom most-used-words-display-percentages-p nil
  "Description .."
  :type 'boolean
  :group 'most-used-words)

;;; In the implementation..
(when most-used-words-display-percentages-p
  ;; Ready to display percentages information in the buffer.
  )
```

So when I have `most-used-words-display-percentages-p` set it to `t`, then display percentages and counts in the buffer as I regularly called `M-x most-used-words-buffer`.

Or a complete separate function, `M-x most-used-words-buffer-with-percentage`, etc.

> I get it. You have to use C-u M-x most-used-words-buffer to get the percentages. Let me know if it works for you.

Sorry, but I don't use other key prefixes like whatever `C-u M-x`. I might just want to call it somewhere else when I could. And I think this way can be more flexible! 😄

**Comment by udyantw** [comment]
Okay. I've broken off the counting and percentage showing funtion as a separate one.
Now M-x most-used-words-buffer-with-counts is the function you want. LDoes this work for you?

**Comment by jcs090218** [comment]
It works! Thank you very much! I appreciated! 😄

**Comment by jcs090218** [comment]
Oh, BTW, I was wonder why ouput have been shift to the right? 😕 (The spaces on the left on each line)

```
                  buffer       33    4.465494%
                    used       32    4.330176%
                    most       31    4.194858%
```

**Comment by udyantw** [comment]
Glad you liked it.

This format was my first shot at making everything aligned. I can look into having the words left-justified. Would that look better?

**Comment by jcs090218** [comment]
If think left-justified would work better in this case. 😄 If you like, you can use `tabulated-list` to display the data, but this might be overkill for this kind of feature. Yet I think this looks much nicer if using it. 👍

**Comment by udyantw** [comment]
I've made a change that left justifies the words when showing the counts and percentages. Is that fine?

**Comment by jcs090218** [comment]
The output is now like this! I like it! There is still gap between text and count, but I think is fine. 😄 

```
and                             2    7.407407%
text                            2    7.407407%
for                             2    7.407407%
```

Thanks! I appreciated!

**Comment by udyantw** [comment]
Great! I'm glad that you liked my work and that I could improve it with your help.
