### ISSUE TITLE
[ERROR] (void-function first)

### ISSUE THREAD

**Issue by jcs090218** [udyantw/most-used-words#4]
I think I get this error in the latest version.

```
(void-function first)
```

I think is on line 104.

**Comment by udyantw** [comment]
Yes. I had forgotten to prefix #'FIRST and #'SECOND from CL-LIB. It should be fixed now.

**Comment by jcs090218** [comment]
Now I got this error `(void-variable for)`. I think is the same reason above? 😕

**Comment by jcs090218** [comment]
And if I tried to eval directly through your current code, I get `(void-function loop)` which is weird. I thought this is common lisp syntax. 😖

**Comment by udyantw** [comment]
Yes. I've replaced LOOP with CL-LOOP, so that the code should eval without errors now. Emacs Lisp style requires us to prefix things from the CL-LIB package.
Please see if this works.

**Comment by jcs090218** [comment]
Thanks! All fixed! 😄
