### ISSUE TITLE
Exceed word displays

### ISSUE THREAD

**Issue by jcs090218** [udyantw/most-used-words#7]
If I have set the display word default to very high (maybe like 100), I think error occurs. I think is good to handle this kind of error! 😄 

**Edit 1:** I think the main error occurs in `most-used-words-buffer-1` since this is the core function. Sorry that I am not very good at common lisp. 😭

**Comment by udyantw** [comment]
I've added some code that handles the case. Light testing shows that functions. But please check.

**Comment by jcs090218** [comment]
Tested! It works perfectly! 😄 I appreciated your work!

Close this now!
