### ISSUE TITLE
Display more useful information.

### ISSUE THREAD

**Issue by jcs090218** [udyantw/most-used-words#9]
Right now if you display more than the unique words it shows the following message.

```
You chose to show more words than there are unique words.  Showing the maximum possible.
```

I think it would be better if you tell user more information about it? Maybe like

```
You chose to display %s words, replace with %s number of unique words
```

The first `%s` will be point to the variable `most-used-words-word-display` and the second `%s` will point to whatever the actual unique words in current buffer after core calculation!

Above message is just a proposal, the main point is to display more information to the user which I think is more handy! 👍

**Comment by udyantw** [comment]
A good suggestion. Please see the latest commit.

**Comment by jcs090218** [comment]
Great! Thanks! I love the new message! 😄
